### ISSUE TITLE
Failed to generate LLVM bitcode

### ISSUE THREAD

**Issue by ahmad2smile** [mbasso/asm-dom-boilerplate#3]
I tried running the boilerplate on Windows 10. Running `npm start` getting this error:

```
> make start

Access denied - SRC
File not found - -NAME
emcc \
        -O3 -Wall -Werror -Wall -Wno-deprecated -Wno-parentheses -Wno-format \
        --bind \
        -include node_modules/asm-dom/cpp/asm-dom.hpp \
         \
        node_modules/asm-dom/cpp/asm-dom.cpp \
        -o temp/app.bc
error: unable to open output file 'temp/app.bc': 'no such file or directory'
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

I ran the command in Administrator command prompt. So `Access denied` shouldn't be the problem.

Node: 8.9.4
npm: 5.6.0
emcc: 1.37.38
GNU make: 4.2

**Comment by mbasso** [comment]
Hi @ahmad2smile,
I'll try to setup the same environment and run `make start`, at the moment I've no idea why it's happening 🤔 It seems that it is unable to write the output file...
I'll update you soon!

**Comment by mbasso** [comment]
I've just tried to reproduce this issue, it seems that this error appears if you use the linux command to search source code files in the src dir. Just open the `Makefile` and follow the instruction on the top, everything should work fine. We should check if there is a way to improve this mechanism instead of asking the user to comment one line and uncomment others...
I've also found an error on windows and I've just pushed a fix, so make sure to pull the latest version of the repository
