### ISSUE TITLE
Production build fails

### ISSUE THREAD

**Issue by s0kil** [mbasso/asm-dom-boilerplate#7]
Here are the errors I get when trying to serve `dist/` folder after a successful build.

![screenshot from 2018-09-18 21-16-13](https://user-images.githubusercontent.com/24403355/45725335-6b016500-bb88-11e8-8f29-0cf812cc57de.png)

**Comment by mbasso** [comment]
Hi @DanielSokil,
I’ve tried to reproduce this issue and it seems that the problem is related to the server. It is serving .wasm files with the wrong Content-Type header. If you configure it to serve them with Content-Type: application/wasm all should work fine. Have you a snippet of code to share? Please let me know if this solves the problem

**Comment by s0kil** [comment]
@mbasso What server do you use to serve `dist` folder?

**Comment by mbasso** [comment]
I've written a small `server.js` file, I'll paste it here

```js
const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();

// tells express to server .wasm files with Content-Type: application/wasm
express.static.mime.define({'application/wasm': ['wasm']});

const port = process.env.PORT || 3000;

app.use(cors({
  origin: process.env.CORS_ALLOW_ORIGIN || '*',
  methods: ['GET', 'PUT', 'POST', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
}));

app.use(express.static(path.resolve(__dirname, './')));

app.listen(port, () => {
  console.log('Server active on port: ', port);
});
```

Just put this in the `dist` folder and run
```bash
npm install express cors
node dist/server.js
```

**Comment by s0kil** [comment]
@mbasso Great! Seems to be working now, Thank you for your help.
