### ISSUE TITLE
Decrease JavaScript size

### ISSUE THREAD

**Issue by s0kil** [mbasso/asm-dom-boilerplate#8]
### What can we do to bundle all JavaScript files into one?
![screenshot from 2018-09-19 20-52-15](https://user-images.githubusercontent.com/24403355/45789504-07da0600-bc4e-11e8-8082-37278a24d826.png)

From what I understand `src.*.js` is the main runtime, `wasm.*.js` loads the `app.*.js` which loads the `*.wasm` file.
What can we do to bundle this into 1 file?
Wouldn't it be simpler if `app*.js` loaded the `wasm` or `asm.js` file?

**Comment by mbasso** [comment]
Hi @DanielSokil,
Yeah that's right.
I think that we can aggregate `src.*.js`, `wasm.*.js` and `asm.*.js` into 1 file. But I don't think that we can also add `app.*.js`.
`app.*.js` are the js files created by emscripten and are useful to load the `wasm` or the `asmjs` version of the app as fallback. So, we have 2 `app.*.js`. Since they are quite heavy we don't want to include both into our bundle, we just want to select the right one, if `WebAssembly` is supported by the browser we will load the first one, otherwise the second.
So, this is the current situation:

```
src.*.js  => wasm.*.js   => app.*.js       => *.wasm
          => asm.*.js    => app.asm.*.js    
```

And this is what we can do:

```
src.*.js  => app.*.js       => *.wasm
          => app.asm.*.js    
```

I'll start working on it as soon as possible.
What do you think about that?

**Comment by mbasso** [comment]
Just pushed the code discussed above.
Let me know if it's ok or you have other ideas 😄

**Comment by s0kil** [comment]
> "app.*.js are the js files created by emscripten and are useful to load the wasm or the asmjs version of the app as fallback."

Is there a way to control how emscripten creates the file? Maybe append the logic needed to `src.*.js`?

**Comment by mbasso** [comment]
Yeah, it is possible to delete `app.asm.*.js` and `app.*.js` files and aggregate them into the `src.*.js`. But I think thats it is not convenient.
When we run `make` we got 2 versions of our app, one compiled in wasm and another compiled in js. They do exactly the same things and are identified by `app.*.js` (wasm version) and `app.asm.*.js` (js version). Only one of these 2 versions is executed by the user. We do this because not every browser supports WebAssembly but we want to run our app on them as well.
At the moment the boilerplate do something like this:

```js
if ('WebAssembly' in window) {
  // load app.*.js
} else {
  // load app.asm.*.js
}
```

So the user download from the network only the needed files to run the right version of the app. If we decide to aggregate them, he will download a lot of additional code that will be never used during the execution. Split it into multiple files however guarantees that he download from the network only the necessary.
There are basically multiple requests but with less data.
Here are the possible scenarios:

```js
// WebAssembly supported by the browser
src.*.js => app.*.js => *.wasm

// WebAssembly not supported by the browser
src.*.js => app.asm.*.js

// if we decide to aggregate them we have something like this
// where the request of *.wasm is optional
src.*.js + app.*.js + app.asm.*.js => *wasm
```

We can think to add to `src.*.js` only `app.*.js` and eventually request `*.wasm` or `app.asm.*.js` but I'm not sure that it is the right choice.
I hope that I have explained it well. Does it make sense?

**Comment by s0kil** [comment]
> We can think to add to `src.*.js` only `app.*.js` and eventually request `*.wasm` or `app.asm.*.js` but I'm not sure that it is the right choice.

Why is this not the right choice? An extra network request is unnecessary especially when a lot more recourses are required to load. And it's going to result in faster startup time.

```bash
src.*.js + app.*.js # One file
# Requests Asm or Wasm version, based on browser support.
=> *wasm
=> app.asm.*.js
```

**Comment by mbasso** [comment]
Because `app.*.js` contains the js code needed only to run the wasm version.
It represents dead code for the one who need to load asm.js.

```js
// common
src.*.js

// wasm version
app.*.js + *.wasm

// asm.js version
app.asm.*.js
```
At the moment `app.*.js` is quite small so, we might think to aggregate it to the other file.
But I think that It will increase its size every time that you use one of the techniques described [here](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#calling-javascript-from-c-c)...

**Comment by s0kil** [comment]
Now I understand, Thanks for your help.

**Comment by mbasso** [comment]
@DanielSokil Thank you for opening this issue and for your interest in asm-dom!
We have removed 2 additional files that were not required, making this project better 😄
If you have other questions or advices please do not hesitate to open another one!
